[build]
builder = "nixpacks"
buildCommand = "cd code && pip install -r requirements.txt"

[deploy]
numReplicas = 1
healthcheckPath = "/api/papers/list"
startCommand = "cd code && gunicorn -w 2 -b 0.0.0.0:$PORT --timeout 120 app:app"
